### ISSUE TITLE
Categoria do frete

### ISSUE THREAD

**Issue by otvoiski** [otvoiski/FreteJob#20]
Categoria do frete: a categoria do frete é representada por um código e deve conter descrição e um percentual, que deve incidir sobre o valor do frete. Por exemplo, entrega rápida (48h) tem aumento de 10%, entrega em super-rápida (24h), tem aumento de 30%, etc. Entrega normal não têm acréscimo no valor.

**Comment by MatheusOliveira1995** [comment]
Implementado.

**Comment by MatheusOliveira1995** [comment]
Implementado.
